version: "3.7"

services:
  reverse-proxy:
    image: traefik:v2.3
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

  # whoami:
  #   image: containous/whoami
  #   container_name: whoami
  #   security_opt:
  #     - no-new-privileges:true
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.njk.localhost`)"
  #     - "traefik.http.routers.whoami.tls=true"
  #   networks:
  #     - proxy

networks:
  proxy:
    external: true
